name: bottom_nav_drawer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets: 
    - assets/png/icon_graph.png
    - assets/png/icon_home.png
    - assets/png/icon_profile.png
    - assets/png/icon_shop.png
    - assets/png/icon_tip.png



